config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create] do
    resources :notes, only: :new
  end
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums do
    resources :tracks, only: :new
  end
  resources :tracks do
    resources :notes, only: :new
  end
  resources :notes

  root to: redirect('/bands')
end

app/models/note.rb
class Note < ApplicationRecord
    validates :user_id, :track_id, :note_text, presence: true

    belongs_to(
        :user,
        class_name: 'User',
        foreign_key: :user_id
    )

    belongs_to(
        :track,
        class_name: 'Track',
        foreign_key: :track_id
    )

    has_one :album, through: :track, source: :album
    has_one :band, through: :track, source: :band
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :require_user!
    before_action :require_note_ownership!, only: %i(destroy)

    def index
        @notes = Note.all
    end

    def show
        @note = Note.find(params[:id])
    end

    def new
        @note = Note.new
    end

    def create
        @note = current_user.notes.new(note_params)
        if @note.save!
            redirect_to note_path(@note)
        else
            flash.now[:errors] = @note.errors.full_messages
            render :new
        end
    end
    
    def edit
        @note = Note.find(params[:id])
    end

    def update
        @note = Note.find(params[:id])
        if @note.update_attributes(note_params)
            redirect_to note_url(@note)
        else
            flash.now[:errors] = @note.errors.full_messages
            render :edit
        end
    end

    def destroy
        @note = Note.find(params[:id])
        @note.destroy
        redirect_to notes_path
    end

    private
    def current_note
        @note ||=
        Note.find(params[:id])
    end

    def note_params
        params.require(:note).permit(:track_id, :note_text)
    end

    def require_note_ownership!
        return if current_user.owns_note?(current_note)
        redirect_to note_url(current_note)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<% action = (note.persisted? ? note_url(note) : notes_url) %>
<% method = (note.persisted? ? :patch : :post) %>
<% message = (note.persisted? ? 'Update!' : 'Create!') %>
<% track_id = (note.persisted? ? note.track.id : params[:track_id].to_i) %>

<%= render 'shared/errors' %>
<form action="<%= action %>" method="post">
    <%= auth_token %>

    <label for="note_track">Track</label>
    <select
        id="note_track"
        name="note[track_id]">
        <option disabled selected>-- select a track --</option>
        <option disabled></option>
        <% Band.all.each do |band| %>
            <option disabled>-- <%= band.name.upcase %> --</option>
            <% band.albums.each do |album| %>
                <option disabled>-- <%= album.title %> --</option>
                <% album.tracks.each do |track| %>
                    <option
                        <%= track.id == track_id ? "selected" : "" %>
                        value="<%= track.id %>">
                        <%= track.title %>
                    </option>
                <% end %>
            <% end %>
        <% end %>
    </select>
    <br>

    <label>
        Note text:
        <textarea name = "note[note_text]"><%= note.note_text %></textarea>
    </label>
    <br>

    <input 
        type="submit"
        value="<%= message %>">

</form>

app/views/notes/edit.html.erb
<h1>Edit note!</h1>

<%= render "form", note: @note %>

app/views/notes/index.html.erb
<h1>Notes</h1>

<% @notes.each do |note| %>
<ul>
    <li>Note for <%= note.track.title %></li>
    <li>Written by <%= note.user.email %></li>
    <li><a href="<%= note_path(note)%>">View note</a></li>
</ul>
<% end %>

<a href="<%= new_note_path %>">Add a new note!</a>

app/views/notes/new.html.erb
<h1>Add a new note!</h1>

<%= render "form", note: @note %>

app/views/notes/show.html.erb
<h1>Note for <%= @note.track.title %></h1>

<p><%= @note.note_text %></p>

<p>Written by <%= @note.user.email %></p>

<form action="<%= edit_note_path(@note) %>" method="get">
    <input type="submit" value="Edit note!"> 
</form>

<% if current_user.owns_note?(@note) %>
    <form action="<%= note_path(@note) %>" method="post">
        <%= auth_token %>
        <input name="_method" value="delete" type="hidden">
        <input type="submit" value="Delete note!"> 
    </form>
<% end %>

<br>

<form action="<%= band_path(@note.band) %>" method="get">
    <input type="submit" value="Back to <%= @note.band.name %>!"> 
</form>

<form action="<%= album_path(@note.album) %>" method="get">
    <input type="submit" value="Back to <%= @note.album.title %>!"> 
</form>

<form action="<%= tracks_path %>" method="get">
    <input type="submit" value="Back to all tracks!"> 
</form>