config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create] do
    resources :notes, only: :new
  end
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums do
    resources :tracks, only: :new
  end
  resources :tracks do
    resources :notes, only: :new
  end
  resources :notes

  root to: redirect('/bands')
end

app/models/track.rb
class Track < ApplicationRecord
    validates :title, :ord, :album_id, :track_type, presence: true
    validates :ord, uniqueness: {scope: :album_id}
    validates :track_type, inclusion: { in: %w(regular bonus)}

    belongs_to(
        :album,
        class_name: 'Album',
        foreign_key: :album_id
    )

    has_many(
        :notes,
        class_name: 'Note',
        foreign_key: :track_id,
        dependent: :destroy
    )

    has_one :band, through: :album, source: :band
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    before_action :require_user!

    def index
        @tracks = Track.all
    end

    def show
        @track = Track.find(params[:id])
    end

    def new
        @track = Track.new
    end

    def create
        @track = Track.new(track_params)
        if @track.save!
            redirect_to track_path(@track)
        else
            flash.now[:errors] = @track.errors.full_messages
            render :new
        end
    end
    
    def edit
        @track = Track.find(params[:id])
    end

    def update
        @track = Track.find(params[:id])
        if @track.update_attributes(track_params)
            redirect_to track_url(@track)
        else
            flash.now[:errors] = @track.errors.full_messages
            render :edit
        end
    end

    def destroy
        @track = Track.find(params[:id])
        @track.destroy
        redirect_to tracks_path
    end

    private
    def track_params
        params.require(:track).permit(:album_id, :title, :ord, :lyrics, :track_type)
    end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<% action = (track.persisted? ? track_url(track) : tracks_url) %>
<% method = (track.persisted? ? :patch : :post) %>
<% message = (track.persisted? ? 'Update!' : 'Create!') %>
<% album_id = (track.persisted? ? track.album.id : params[:album_id].to_i) %>
<% band_id = (track.persisted? ? track.band.id : (params[:album_id] ? Album.find(params[:album_id]).band.id : nil)) %>

<%= render 'shared/errors' %>
<form action="<%= action %>" method="post">
    <%= auth_token %>
    <input
        name="_method"
        value="<%= method %>"
        type="hidden">
    
    <label for="track_title">Title</label>
    <input
        id="track_title"
        name="track[title]"
        value="<%= track.title %>"
        type="text">
    <br>

    <label for="track_ord">Track number</label>
    <input
        id="track_ord"
        name="track[ord]"
        value="<%= track.ord %>"
        type="text">
    <br>

    <label for="track_album_id">Album</label>
    <select
        id="track_album_id"
        name="track[album_id]">
        <option disabled selected>-- select an album --</option>
        <option disabled></option>
        <% Band.all.each do |band| %>
            <option disabled>-- <%= band.name.upcase %> --</option>
            <% band.albums.each do |album| %>
                <option
                    <%= album.id == album_id ? "selected" : "" %>
                    value="<%= album.id %>">
                    <%= album.title %>
                </option>
            <% end %>
        <% end %>
    </select>
    <br>

    <input
        type = "radio"
        name = "track[track_type]"
        id = "track_regular"
        value = "regular"
        <%= track.track_type == 'regular' ? "checked" : "" %>>
    <label for="track_regular">Regular track</label>
    <input
        type = "radio"
        name = "track[track_type]"
        id = "track_bonus"
        value = "bonus"
        <%= track.track_type == 'bonus' ? "checked" : "" %>>
    <label for="track_bonus">Bonus track</label>
    <br>

    <label>
        Lyrics
        <textarea name = "track[lyrics]"><%= track.lyrics %></textarea>
    </label>
    <br>

    <input 
        type="submit"
        value="<%= message %>">

</form>

app/views/tracks/edit.html.erb
<h1>Edit track!</h1>

<%= render "form", track: @track %>

app/views/tracks/index.html.erb
<h1>Tracks</h1>

<% @tracks.each do |track| %>
<ul>
    <li><%= track.title %></li>
    <li><a href="<%= track_path(track)%>">View track</a></li>
</ul>
<% end %>

<a href="<%= new_track_path %>">Add a new track!</a>

app/views/tracks/new.html.erb
<h1>Add a new track!</h1>

<%= render "form", track: @track %>

app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>

<table>
    <tr>
        <th>Album</th>
        <td><%= @track.album.title%></td>
    </tr>
    <tr>
        <th>Band</th>
        <td><%= @track.band.name%></td>
    </tr>
    <tr>
        <th>Track Number</th>
        <td><%= @track.ord%></td>
    </tr>
    <tr>
        <th>Lyrics</th>
        <td><%= ugly_lyrics(@track.lyrics) %></td>
    </tr>
    <tr>
        <th>Track Type</th>
        <td><%= @track.track_type%></td>
    </tr>
</table>

<h2>Notes</h2>
<% @track.notes.each do |note| %>
    <h3><a href="<%= note_path(note) %>">Note by <%= note.user.email %></a></h3>
    <p><%= note.note_text %></p>
<% end %>
<form action="<%= new_track_note_path(@track) %>" method="get">
    <input type="submit" value="Add note!"> 
</form>
<br>
<br>

<form action="<%= edit_track_path(@track) %>" method="get">
    <input type="submit" value="Edit track!"> 
</form>

<form action="<%= track_path(@track) %>" method="post">
    <%= auth_token %>
    <input name="_method" value="delete" type="hidden">
    <input type="submit" value="Delete track!"> 
</form>

<br>

<form action="<%= band_path(@track.band) %>" method="get">
    <input type="submit" value="Back to <%= @track.band.name %>!"> 
</form>

<form action="<%= album_path(@track.album) %>" method="get">
    <input type="submit" value="Back to <%= @track.album.title %>!"> 
</form>

<form action="<%= tracks_path %>" method="get">
    <input type="submit" value="Back to all tracks!"> 
</form>