config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create] do
    resources :notes, only: :new
  end
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums do
    resources :tracks, only: :new
  end
  resources :tracks do
    resources :notes, only: :new
  end
  resources :notes

  root to: redirect('/bands')
end

app/models/album.rb
class Album < ApplicationRecord
    validates :title, :year, :band_id, :album_type, presence: true
    validates :title, uniqueness: {scope: :band_id}
    validates :album_type, inclusion: { in: %w(studio live)}


    belongs_to(
        :band,
        class_name: 'Band',
        foreign_key: :band_id
    )

    has_many(
        :tracks,
        class_name: 'Track',
        foreign_key: :album_id,
        dependent: :destroy
    )

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :require_user!
    
    def index
        @albums = Album.all
    end

    def show
        @album = Album.find(params[:id])
    end

    def new
        @album = Album.new
    end

    def create
        @album = Album.new(album_params)
        if @album.save
            redirect_to album_path(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end
    
    def edit
        @album = Album.find(params[:id])
    end

    def update
        @album = Album.find(params[:id])
        if @album.update_attributes(album_params)
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :edit
        end
    end

    def destroy
        @album = Album.find(params[:id])
        @album.destroy
        redirect_to albums_path
    end

    private
    def album_params
        params.require(:album).permit(:title, :year, :band_id, :is_studio)
    end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/views/albums/_form.html.erb
<% action = (album.persisted? ? album_url(album) : albums_url) %>
<% method = (album.persisted? ? :patch : :post) %>
<% message = (album.persisted? ? 'Update!' : 'Create!') %>
<% band_id = (album.persisted? ? album.band.id : params[:band_id].to_i) %>

<%= render 'shared/errors' %>
<form action="<%= action %>" method="post">
    <%= auth_token %>
    <input
        name="_method"
        value="<%= method %>"
        type="hidden">
    
    <label for="album_title">Title</label>
    <input
        id="album_title"
        name="album[title]"
        value="<%= album.title %>"
        type="text">
    <br>

    <label for="album_year">Year</label>
    <input
        id="album_year"
        name="album[year]"
        value="<%= album.year %>"
        type="text">
    <br>

    <label for="album_band_id">Band</label>
    <select
        id="album_band_id"
        name="album[band_id]">
        <option disabled selected>-- select a band --</option>
        <% Band.all.each do |band| %>
            <option
                <%= band.id == band_id ? "selected" : "" %>
                value="<%= band.id %>">
                <%= band.name %>
            </option>
        <% end %>
    </select>
    <br>

    <input
        type = "radio"
        name = "album[album_type]"
        id = "album_studio"
        value = "studio"
        <%= album.album_type == 'studio' ? "checked" : "" %>>
    <label for="album_studio">Studio</label>
    <input
        type = "radio"
        name = "album[album_type]"
        id = "album_live"
        value = "live"
        <%= album.album_type == 'live' ? "checked" : "" %>>
    <label for="album_live">Live</label>
    <br>

    <input 
        type="submit"
        value="<%= message %>">

</form>

app/views/albums/edit.html.erb
<h1>Edit your album!</h1>

<%= render "form", album: @album %>

app/views/albums/index.html.erb
<h1>Albums</h1>

<% @albums.each do |album| %>
<ul>
    <li><%= album.title %></li>
    <li><a href="<%= album_path(album)%>">View album</a></li>
</ul>
<% end %>

<a href="<%= new_album_path %>">Add a new album!</a>

app/views/albums/new.html.erb
<h1>Add a new album!</h1>

<%= render "form", album: @album %>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>

<table>
    <tr>
        <th>Year</th>
        <td><%= @album.year%></td>
    </tr>
    <tr>
        <th>Band</th>
        <td><%= @album.band.name%></td>
    </tr>
    <tr>
        <th>Type</th>
        <td><%= @album.album_type%></td>
    </tr>
    <tr>
        <th>Tracks</th>
        <td>
            <% @album.tracks.each do |track|%>
                <%= track.ord %>
                <%= track.title %>
                <a href="<%= track_path(track) %>">View track</a>
                <br>
            <% end %>
        </td>
    </tr>
</table>

<form action="<%= edit_album_path(@album) %>" method="get">
    <input type="submit" value="Edit album!"> 
</form>

<form action="<%= album_path(@album) %>" method="post">
    <%= auth_token %>
    <input name="_method" value="delete" type="hidden">
    <input type="submit" value="Delete album!"> 
</form>

<br>

<form action="<%= new_album_track_path(@album) %>" method="get">
    <input type="submit" value="Add track!"> 
</form>

<br>

<form action="<%= band_path(@album.band) %>" method="get">
    <input type="submit" value="Back to <%= @album.band.name %>!"> 
</form>

<form action="<%= albums_path %>" method="get">
    <input type="submit" value="Back to all albums!"> 
</form>