config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :new, :create] do
    resources :notes, only: :new
  end
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums do
    resources :tracks, only: :new
  end
  resources :tracks do
    resources :notes, only: :new
  end
  resources :notes

  root to: redirect('/bands')
end

app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many(
        :albums,
        class_name: 'Album',
        foreign_key: :band_id,
        dependent: :destroy
    )

    has_many :tracks, through: :albums, source: :tracks

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
    before_action :require_user!
    
    def index
        @bands = Band.all
    end

    def show
        @band = Band.find(params[:id])
    end

    def new
        @band = Band.new
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to band_path(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end
    
    def edit
        @band = Band.find(params[:id])
    end

    def update
        @band = Band.find(params[:id])
        if @band.update_attributes(band_params)
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_path
    end

    private
    def band_params
        params.require(:band).permit(:name)
    end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band) : bands_url) %>
<% method = (band.persisted? ? :patch : :post) %>
<% message = (band.persisted? ? 'Update!' : 'Create!') %>

<%= render 'shared/errors' %>
<form action="<%= action %>" method="post">
    <%= auth_token %>
    <input
        name="_method"
        value="<%= method %>"
        type="hidden">
    
    <label for="band_name">Name</label>
    <input
        id="band_name"
        name="band[name]"
        value="<%= band.name %>"
        type="text">
    <br>

    <input 
        type="submit"
        value="<%= message %>">

</form>

app/views/bands/edit.html.erb
<h1>Edit your album!</h1>

<%= render "form", album: @album %>

app/views/bands/index.html.erb
<h1>Bands</h1>

<% @bands.each do |band| %>
<ul>
    <li><%= band.name %></li>
    <li><a href="<%= band_path(band)%>">View band</a></li>
</ul>
<% end %>

<a href="<%= new_band_path %>">Add a new band!</a>

app/views/bands/new.html.erb
<h1>Add a new album!</h1>

<%= render "form", album: @album %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<% @band.albums.each do |album| %>
<ul>
    <li><%= album.title %></li>
    <li><%= album.year %></li>
    <li><a href="<%= album_path(album)%>">View album</a></li>
</ul>
<% end %>

<form action="<%= edit_band_path(@band) %>" method="get">
    <input type="submit" value="Edit band!"> 
</form>

<form action="<%= new_band_album_path(@band) %>" method="get">
    <input type="submit" value="Add album!"> 
</form>
<br>

<form action="<%= band_path(@band) %>" method="post">
    <%= auth_token %>
    <input name="_method" value="delete" type="hidden">
    <input type="submit" value="Delete band!"> 
</form>

<br>

<form action="<%= bands_path %>" method="get">
    <input type="submit" value="Back to all bands!"> 
</form>